// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaGhPHlz9dwo1F1ty6wXgLPq0trjuG3Jc',
    appId: '1:1036081452587:web:12ee9b19bb47337d827c6e',
    messagingSenderId: '1036081452587',
    projectId: 'spiceslice-7c389',
    authDomain: 'spiceslice-7c389.firebaseapp.com',
    storageBucket: 'spiceslice-7c389.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKjgYT-_jZ8V1NDk0ey_HEKcATqSvIhP8',
    appId: '1:1036081452587:android:9e4793a321544d9d827c6e',
    messagingSenderId: '1036081452587',
    projectId: 'spiceslice-7c389',
    storageBucket: 'spiceslice-7c389.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaHx0XL5CamgPGdkp53wpHbzDOK9QTLnA',
    appId: '1:1036081452587:ios:4c8a73aae0c60ce0827c6e',
    messagingSenderId: '1036081452587',
    projectId: 'spiceslice-7c389',
    storageBucket: 'spiceslice-7c389.firebasestorage.app',
    iosBundleId: 'com.spiceslice.recipeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaHx0XL5CamgPGdkp53wpHbzDOK9QTLnA',
    appId: '1:1036081452587:ios:14fbf1aa701413e6827c6e',
    messagingSenderId: '1036081452587',
    projectId: 'spiceslice-7c389',
    storageBucket: 'spiceslice-7c389.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaGhPHlz9dwo1F1ty6wXgLPq0trjuG3Jc',
    appId: '1:1036081452587:web:6501b30da020a36e827c6e',
    messagingSenderId: '1036081452587',
    projectId: 'spiceslice-7c389',
    authDomain: 'spiceslice-7c389.firebaseapp.com',
    storageBucket: 'spiceslice-7c389.firebasestorage.app',
  );
}
